- name: install borgbackup
  become: true
  hosts: all
  tasks:
    - name: install borg
      apt:
        name: borgbackup
        state: latest

- name: backup_vm
  become: true
  hosts: backup
  tasks:
    - name: create dir
      file: 
        path: /var/backup
        state: directory
        mode: '0755'
    - name: Create a ext4 filesystem on /dev/sdb
      filesystem:
        fstype: ext4
        dev: /dev/sdb
    - name: mount disk
      mount:
        path: /var/backup
        src: /dev/sdb
        fstype: ext4
        state: mounted
    - name: create 
      user:
        name: borg

    - name: chown dir
      file:
        path: /var/backup  
        owner: borg
        group: borg
        mode: '0755'

    - name: create dir
      file: 
        path:  /home/borg/.ssh
        state: directory

    - name: chown dir ssh
      file:
        path: .ssh
          #  mode: '700'
       
    - name: create file
      file: 
        path: /home/borg/.ssh/authorized_keys
        state: touch
        owner: borg
        group: borg
        #mode: '600'

- name: client_vm
  become: true
  hosts: client
  tasks:

    #  - name: init borg
    #   command: borg init --encryption=repokey borg@192.168.56.10:/var/backup/
