- name: install borgbackup
  become: true
  hosts: all
  tasks:
    - name: install borg
      apt:
        pkg: 
          - borgbackup
          - rsync

- name: backup_server
  become: true
  hosts: backup
  tasks:
    - name: create dir
      file: 
        path: /var/backup
        state: directory
        mode: '0755'

    - name: Create a ext4 filesystem on /dev/sdb
      filesystem:
        fstype: ext4
        dev: /dev/sdb

    - name: mount disk
      mount:
        path: /var/backup
        src: /dev/sdb
        fstype: ext4
        state: mounted

    - name: create 
      user:
        name: borg

    - name: chown dir
      file:
        path: /var/backup  
        owner: borg
        group: borg
        mode: '0755'

    - name: create dir
      file: 
        path:  /home/borg/.ssh
        state: directory

    - name: chown dir ssh
      file:
        path: .ssh
        mode: '775'
       
    - name: create file
      file: 
        path: /home/borg/.ssh/authorized_keys
        state: touch
        owner: borg
        group: borg
        mode: '775'

- name: client_vm
  become: true
  hosts: client
  tasks:
   - name: Generate an ssh-keygen
     openssh_keypair:
       path: .ssh/id_rsa
       owner: vagrant
       group: vagrant
     
   - name: Fetch public SSH key from keygen_vm
     fetch:
       src: /home/vagrant/.ssh/id_rsa.pub
       dest: id_rsa.pub
       flat: yes

   - set_fact:
       public_key: "{{ lookup('file', 'id_rsa.pub') }}"

- hosts: backup
  tasks:
    
    - name: Copy SSH public key to /home/borg/.ssh/authorized_keys
      authorized_key:
        user: borg
        key: "{{ hostvars['client'].public_key }}"
        state: present
      become: yes

    - name: init borg
      command: 'borg init --encryption=repokey borg@192.168.10.56:/var/backup/'
