---
# tasks file for nginx_otus
    - name: print linux
      ansible.builtin.debug:
        var: "ansible_os_family"
    
    - name: Install EPEL Repo package from standard repo
      ansible.builtin.yum:
        name: epel-release
        state: present
      tags:
        - epel-package
        - packages     
      when: ansible_os_family == "RedHat"
      
    - name: NGINX | Install NGINX package from EPEL Repo
      ansible.builtin.yum:
        name: nginx
        state: latest
      notify:
        - restart nginx
      tags:
        - nginx-package
        - packages
      when: ansible_os_family == "RedHat"
      
    - name: NGINX for Deb
      ansible.builtin.apt:
        name: nginx
        state: latest
      notify:
        - restart nginx  
      when: ansible_os_family == "Debian"

    - name: NGINX | Create NGINX config file from template
      ansible.builtin.template:
        src: /home/localadm/ansible/nginx.conf.j2
        dest: /etc/nginx/nginx.conf 
      notify:
        - restart nginx  
      tags:
        - nginx-configuration
