---
# handlers file for nginx_otus
- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
    
- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
